<a href="https://colab.research.google.com/github/rubabshz/Rubab_INFO5731_Spring2020/blob/main/Rubab_In_class_exercise_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **The second In-class-exercise (1/27/2021, 20 points in total)**


(1) Write a Python program to find the duplicate elements in a given array of integers. Return -1 If there are no such elements. (4 points)

In [31]:
# write your answer here:
   
def duplicate_element(an_array):

 arr_set = set()
 no_duplicates = -1
 x = len(an_array)

 for i in range(x):

      if an_array[i] in arr_set:
       return an_array[i]

      else:
       arr_set.add(an_array[i])

 return no_duplicates 


print(duplicate_element([1,2,3,3,4,5]))
print(duplicate_element([1,2,3,4,5]))
 


3
-1


(2) Write a Python program to select all the Sundays of a specified year. (4 points)



In [141]:
# write your answer here
from datetime import date, timedelta

def sundays(year):
  cal_dt = date(year, 1, 1)      
  cal_dt += timedelta(days = 7 - cal_dt.isoweekday())  
  while cal_dt.year == year:
    yield cal_dt
    cal_dt += timedelta(days = 7)
          
for x in sundays(2000):
   print("Sunday: ", x)



Sunday:  2000-01-02
Sunday:  2000-01-09
Sunday:  2000-01-16
Sunday:  2000-01-23
Sunday:  2000-01-30
Sunday:  2000-02-06
Sunday:  2000-02-13
Sunday:  2000-02-20
Sunday:  2000-02-27
Sunday:  2000-03-05
Sunday:  2000-03-12
Sunday:  2000-03-19
Sunday:  2000-03-26
Sunday:  2000-04-02
Sunday:  2000-04-09
Sunday:  2000-04-16
Sunday:  2000-04-23
Sunday:  2000-04-30
Sunday:  2000-05-07
Sunday:  2000-05-14
Sunday:  2000-05-21
Sunday:  2000-05-28
Sunday:  2000-06-04
Sunday:  2000-06-11
Sunday:  2000-06-18
Sunday:  2000-06-25
Sunday:  2000-07-02
Sunday:  2000-07-09
Sunday:  2000-07-16
Sunday:  2000-07-23
Sunday:  2000-07-30
Sunday:  2000-08-06
Sunday:  2000-08-13
Sunday:  2000-08-20
Sunday:  2000-08-27
Sunday:  2000-09-03
Sunday:  2000-09-10
Sunday:  2000-09-17
Sunday:  2000-09-24
Sunday:  2000-10-01
Sunday:  2000-10-08
Sunday:  2000-10-15
Sunday:  2000-10-22
Sunday:  2000-10-29
Sunday:  2000-11-05
Sunday:  2000-11-12
Sunday:  2000-11-19
Sunday:  2000-11-26
Sunday:  2000-12-03
Sunday:  2000-12-10


(3) Python files reading and writing. Download the “[exercise_02_data _collection.zip](https://github.com/unt-iialab/info5731_spring2021/blob/main/class_exercises/exercise_02_data_collection.zip)” to your local and un-zip it.

*   Write a program to read all the txt files and save the sentences in all the files into one csv file with two columns, the first column is sentence id (txt file name+sentence line number), the second column is the sentence text content. (4 points)
*   Remove all the punctuations from the sentences, save the processed sentences into a new column in the same csv file. (4 points)
*   Ask the user to enter a word, return all the sentences that include this word, three kinds of information should be returned: sentence id, sentence text content, the count that user input word appear in the sentence. (4 points)



In [133]:
# write your answer here

import csv

with open("output.csv","w") as o_File:
    holder = csv.writer(o_File,delimiter=',')

    i = 1
    while i <= 100: 

        input_file = "/content/"+"ARTHROTEC."+str(i)+".txt" 
        output_line = "ARTHROTEC."+str(i)
        i_File = open(input_file).read() 
        sentences = i_File.split('\n') 
        for x in sentences: 
            if x == '':
                sentences.remove(x) 
        for x in sentences: 
            sentence_num = output_line +" " +str(sentences.index(x)+1) 

            holder.writerow([sentence_num,x]) 
        i += 1

###############################################################################

import csv
import re
empList = [] 
with open("output.csv",'r') as i_File:
    file_reader = csv.reader(i_File) 
    for row in file_reader: 
        newline = re.sub(r"[^a-zA-Z\s\']","",row[1]) 
        newline = re.sub("\s\s"," ",newline) 
        row.append(newline) 
        empList.append(row) 
with open("output.csv","w") as o_File:
    file_writer = csv.writer(o_File,delimiter=',') 
    file_writer.writerows(empList) 

###############################################################################

import csv
import re
user = input("Type a Word: ") 
with open("output.csv",'r') as i_File:
    file_reader = csv.reader(i_File) 
    for row in file_reader: 
        userEntry = " "+user+" "
        if userEntry in row[2]:
            result = re.findall(userEntry,row[2])
            print(row[0],row[1],len(result))



Type a Word: pain
ARTHROTEC.2 2 Did not seem to make a lot of difference to the pain it was supposed to be treating. 1
ARTHROTEC.2 3 Stopped taking it after 13 days, prefer the pain in my forearms. 1
ARTHROTEC.3 1 Constipation right from the start and in ladt 4 weeks extreme joint pain at night (just few hours after taking tablets). 1
ARTHROTEC.3 6 Arthrotec was supposed to ease my pain not make it worse. 1
ARTHROTEC.3 7 Have stopped taking and immediatedly muscle/joint pain eased and sleeping much better. 1
ARTHROTEC.4 5 It did help with the pain I experience with the pinched nerve, but it is not worth it to me to continue. 1
ARTHROTEC.6 2 After the second pill the same progression of symptoms only now the abdominal gas,cramps and pain would be with me all day. 1
ARTHROTEC.6 4 The only good thing I can say about Arthrotec is that I did notice pain relief but I won't put up with the side effects on a daily basis since I spent a long time getting rid of a reflux problem in the past. 1
A

(4) Install packages nltk, numpy, scipy, pandas, and sklearn on Google Colab. Write a program to test whether they are installed successfully. (3 points for extra)

In [117]:
# NLTK

! pip install nltk
from nltk.tokenize import wordpunct_tokenize

word_sentence = "I am working on the in-class exercise number two!"
print(wordpunct_tokenize(word_sentence))  



['I', 'am', 'working', 'on', 'the', 'in', '-', 'class', 'exercise', 'number', 'two', '!']


In [134]:
# Numpy
! pip install Numpy
import numpy as np
arr = np.array([[1,2],[3,4]])
print(arr.shape)

 


(2, 2)


In [135]:
#Scipy
! pip install Scipy

from scipy import stats
import numpy as np
x = np.array([1,2,3,4,5,6,7,8,9])
max = x.max()
min = x.min()
mean = x.mean()
var = x.var() 
print (max,min,mean,var)




9 1 5.0 6.666666666666667


In [136]:
#Pandas
! pip install Pandas
import pandas as pd

data = pd.Series([0.01,0.02,0.03,0.04])
print(data)


0    0.01
1    0.02
2    0.03
3    0.04
dtype: float64


In [137]:
#Sklearn
! pip install Sklearn
from sklearn import datasets

x = datasets.load_iris()
y = datasets.load_digits()
while x != 0:
 print((y.data)**2)
 break


[[  0.   0.  25. ...   0.   0.   0.]
 [  0.   0.   0. ... 100.   0.   0.]
 [  0.   0.   0. ... 256.  81.   0.]
 ...
 [  0.   0.   1. ...  36.   0.   0.]
 [  0.   0.   4. ... 144.   0.   0.]
 [  0.   0. 100. ... 144.   1.   0.]]
